[project]
name = "maptap"
version = "0.1.0"
description = "MapTap difficulty metric"
readme = "README.md"
authors = [
    { name = "Bernardo Lustrini", email = "blustrini@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
maptap = "maptap:main"

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
